services:
#  pixel_battle_backend:
#    container_name: pixel_battle_backend
#    build:
#      context: .
#      dockerfile: Dockerfile
#    restart: on-failure
#    depends_on:
#      - pixel_battle_postgres
#      - pixel_battle_redis
#    environment:
#      FRONTEND_URL: http://localhost:4200
#      SERVER_PORT: 8085
#      DB_URL: jdbc:postgresql://pixel_battle_postgres:5432/pixel_battle
#      DB_USER: postgres
#      DB_PASS: 123321
#      REDIS_HOST: redis://pixel_battle_redis:6379
#    ports:
#      - "8085:8085"
  pixel_battle_postgres:
    image: postgres:latest
    container_name: pixel_battle_postgres
    environment:
      POSTGRES_DB: pixel_battle
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123321
    volumes:
      - pixel_battle_postgres:/var/lib/postgresql/data
    ports:
      - "6543:5432"
  pixel_battle_redis:
    image: bitnami/redis:latest
    container_name: pixel_battle_redis
    command: redis-server --loglevel debug --protected-mode no
    ports:
      - "6379:6379"
volumes:
  pixel_battle_postgres:
