settings:
  frontend-url: ${FRONTEND_URL:http://localhost:4200}
  cookie-token-key: '{"kty":"oct","k":"pRBbJ5V5Jme3DrVU-bBs_EodILdMV4G-HA6SwQ9Dbkw","alg":"A256GCMKW"}'
  server:
    port: ${SERVER_PORT:8085}
  db:
    url: ${DB_URL:jdbc:postgresql://localhost:6543/pixel_battle}
    username: ${DB_USER:postgres}
    password: ${DB_PASS:123321}
  redis:
    host: ${REDIS_HOST:redis://localhost:6379}

server:
  servlet:
    context-path: /api
  port: ${settings.server.port}

spring:
  sql:
    init:
      mode: always
      separator: ^^^ END OF SCRIPT ^^^
  application:
    name: core-service
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${settings.db.url}
    username: ${settings.db.username}
    password: ${settings.db.password}
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        jdbc:
          batch_size: 500
          order_inserts: true
          order_updates: true
  data:
    redis:
      url: ${settings.redis.host}


springdoc:
  swagger-ui:
    path: /swagger
  api-docs:
    path: /api-docs

pixel-battle:
  request-timeout: 2
  create-new: true
  rows: 100
  columns: 50

logging:
  level:
    org.springframework.data.redis: TRACE
