settings:
  server:
    port: ${SERVER_PORT}
  db:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASS}

server:
  servlet:
    context-path: /api
  port: ${settings.server.port}

spring:
  sql:
    init:
      mode: always
      separator: ^^^ END OF SCRIPT ^^^
  application:
    name: core-service
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${settings.db.url}
    username: ${settings.db.username}
    password: ${settings.db.password}
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        jdbc:
          batch_size: 500
          order_inserts: true
          order_updates: true

springdoc:
  swagger-ui:
    path: /swagger
  api-docs:
    path: /api-docs

pixel-battle:
  request-timeout: 2
  create-new: true
  rows: 100
  columns: 50

